"""add label column to segments

Revision ID: 3a2c868476b7
Revises: b2e93e11bdc0
Create Date: 2026-09-16 21:33:04.430306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2c868476b7'
down_revision: Union[str, None] = 'b2e93e11bdc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segments', sa.Column('label', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segments', 'label')
    # ### end Alembic commands ###
