"""create initial tables

Revision ID: 444442f442c2
Revises: 
Create Date: 2026-05-17 16:16:53.366387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '444442f442c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('project_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('full_video_path', sa.String(length=512), nullable=True),
    sa.Column('pdf_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_project_id'), 'sessions', ['project_id'], unique=False)
    op.create_table('chunks',
    sa.Column('chunk_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('t_start', sa.Float(), nullable=False),
    sa.Column('t_end', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index(op.f('ix_chunks_session_id'), 'chunks', ['session_id'], unique=False)
    op.create_table('segments',
    sa.Column('segment_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('t_start', sa.Float(), nullable=False),
    sa.Column('t_end', sa.Float(), nullable=False),
    sa.Column('slide_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segment_id')
    )
    op.create_index(op.f('ix_segments_session_id'), 'segments', ['session_id'], unique=False)
    op.create_table('stt_sentences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('t_start', sa.Float(), nullable=False),
    sa.Column('t_end', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stt_sentences_session_id'), 'stt_sentences', ['session_id'], unique=False)
    op.create_table('voice_raws',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('total_duration', sa.Float(), nullable=False),
    sa.Column('silence_segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('filler_words', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('feedbacks',
    sa.Column('segment_id', sa.BigInteger(), nullable=False),
    sa.Column('score_delivery', sa.Float(), nullable=True),
    sa.Column('score_fluency', sa.Float(), nullable=True),
    sa.Column('score_motion', sa.Float(), nullable=True),
    sa.Column('fb_delivery', sa.Text(), nullable=True),
    sa.Column('fb_fluency', sa.Text(), nullable=True),
    sa.Column('fb_motion', sa.Text(), nullable=True),
    sa.Column('fb_overall', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.segment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segment_id')
    )
    op.create_table('segment_analyses',
    sa.Column('segment_id', sa.BigInteger(), nullable=False),
    sa.Column('stt_text', sa.Text(), nullable=True),
    sa.Column('wpm', sa.Float(), nullable=True),
    sa.Column('silence_count', sa.Integer(), nullable=True),
    sa.Column('filler_count', sa.Integer(), nullable=True),
    sa.Column('posture', sa.Text(), nullable=True),
    sa.Column('eye_contact', sa.Text(), nullable=True),
    sa.Column('gesture', sa.Text(), nullable=True),
    sa.Column('motion_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.segment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segment_id')
    )
    op.create_table('session_summaries',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('total_duration', sa.Float(), nullable=True),
    sa.Column('segment_count', sa.Integer(), nullable=True),
    sa.Column('overall_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_filler_count', sa.Integer(), nullable=True),
    sa.Column('avg_wpm', sa.Float(), nullable=True),
    sa.Column('best_segment_id', sa.BigInteger(), nullable=True),
    sa.Column('worst_segment_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['best_segment_id'], ['segments.segment_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worst_segment_id'], ['segments.segment_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_summaries')
    op.drop_table('segment_analyses')
    op.drop_table('feedbacks')
    op.drop_table('voice_raws')
    op.drop_index(op.f('ix_stt_sentences_session_id'), table_name='stt_sentences')
    op.drop_table('stt_sentences')
    op.drop_index(op.f('ix_segments_session_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_chunks_session_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_sessions_project_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
