"""add silence ratio and gesture totals to segment_analyses

Revision ID: 868def7d88f9
Revises: 3a2c868476b7
Create Date: 2026-09-17 22:23:42.086182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '868def7d88f9'
down_revision: Union[str, None] = '3a2c868476b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment_analyses', sa.Column('silence_ratio', sa.Float(), nullable=True))
    op.add_column('segment_analyses', sa.Column('positive_gesture_count', sa.Integer(), nullable=True))
    op.add_column('segment_analyses', sa.Column('negative_gesture_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segment_analyses', 'negative_gesture_count')
    op.drop_column('segment_analyses', 'positive_gesture_count')
    op.drop_column('segment_analyses', 'silence_ratio')
    # ### end Alembic commands ###
