"""add strengths and improvements to feedbacks

Revision ID: 8b4499cd29e3
Revises: ba342bb649d8
Create Date: 2026-09-20 00:22:46.433306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b4499cd29e3'
down_revision: Union[str, None] = 'ba342bb649d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('feedbacks', sa.Column('improvements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'improvements')
    op.drop_column('feedbacks', 'strengths')
    # ### end Alembic commands ###
