"""add deleted_at to projects (trash)

Revision ID: aef99971920a
Revises: 3a2c868476b7
Create Date: 2026-09-17 22:50:59.741225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef99971920a'
down_revision: Union[str, None] = '3a2c868476b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_projects_deleted_at'), 'projects', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_deleted_at'), table_name='projects')
    op.drop_column('projects', 'deleted_at')
    # ### end Alembic commands ###
