"""add chunk_analyses, refactor segment_analyses
  motion fields to JSONB counts

Revision ID: b856588e40a8
Revises: 444442f442c2
Create Date: 2026-05-22 03:15:56.359728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b856588e40a8'
down_revision: Union[str, None] = '444442f442c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk_analyses',
    sa.Column('chunk_id', sa.BigInteger(), nullable=False),
    sa.Column('posture', sa.String(length=32), nullable=True),
    sa.Column('eye_contact', sa.String(length=32), nullable=True),
    sa.Column('gesture', sa.String(length=32), nullable=True),
    sa.Column('gesture_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.add_column('segment_analyses', sa.Column('gesture_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('segment_analyses', sa.Column('posture_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('segment_analyses', sa.Column('eye_contact_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('segment_analyses', 'eye_contact')
    op.drop_column('segment_analyses', 'gesture')
    op.drop_column('segment_analyses', 'posture')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment_analyses', sa.Column('posture', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('segment_analyses', sa.Column('gesture', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('segment_analyses', sa.Column('eye_contact', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('segment_analyses', 'eye_contact_counts')
    op.drop_column('segment_analyses', 'posture_counts')
    op.drop_column('segment_analyses', 'gesture_counts')
    op.drop_table('chunk_analyses')
    # ### end Alembic commands ###
